export const eventTypes = {
  // auth
  LOGGED_IN: "LOGGED_IN",
  FAILED_TO_LOGIN: "FAILED_TO_LOGIN",
  LOGGED_OUT: "LOGGED_OUT",
  FAILED_TO_LOGOUT: "FAILED_TO_LOGOUT",
  SIGNED_UP: "SIGNED_UP",
  FAILED_TO_SIGN_UP: "FAILED_TO_SIGN_UP",

  // notes
  CREATED_NOTE: "CREATED_NOTE",
  FAILED_TO_CREATE_NOTE: "FAILED_TO_CREATE_NOTE",
  UPDATED_NOTE: "UPDATED_NOTE",
  FAILED_TO_UPDATE_NOTE: "FAILED_TO_UPDATE_NOTE",
  DELETED_NOTE: "DELETED_NOTE",
  FAILED_TO_DELETE_NOTE: "FAILED_TO_DELETE_NOTE"
} as const;
