const eventTypes = {
  LOGGED_IN: "LOGGED_IN",
  FAILED_TO_LOGIN: "FAILED_TO_LOGIN",
  LOGGED_OUT: "LOGGED_OUT",
  FAILED_TO_LOGOUT: "FAILED_TO_LOGOUT",
  SIGNED_UP: "SIGNED_UP",
  FAILED_TO_SIGN_UP: "FAILED_TO_SIGN_UP"
} as const;

export default {
  eventTypes
};
