const eventTypes = {
  CREATED_NOTE: "CREATED_NOTE",
  FAILED_TO_CREATE_NOTE: "FAILED_TO_CREATE_NOTE",
  UPDATED_NOTE: "UPDATED_NOTE",
  FAILED_TO_UPDATE_NOTE: "FAILED_TO_UPDATE_NOTE",
  DELETED_NOTE: "DELETED_NOTE",
  FAILED_TO_DELETE_NOTE: "FAILED_TO_DELETE_NOTE"
} as const;

export default {
  eventTypes
};
